function tau_frcn = F_vctr_fcn(in1,in2)
%F_vctr_fcn
%    TAU_FRCN = F_vctr_fcn(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    12-Aug-2025 14:05:27

pi_frcn_11 = in2(1,:);
pi_frcn_21 = in2(2,:);
pi_frcn_31 = in2(3,:);
pi_frcn_41 = in2(4,:);
pi_frcn_51 = in2(5,:);
pi_frcn_61 = in2(6,:);
pi_frcn_71 = in2(7,:);
pi_frcn_81 = in2(8,:);
pi_frcn_91 = in2(9,:);
pi_frcn_101 = in2(10,:);
pi_frcn_111 = in2(11,:);
pi_frcn_121 = in2(12,:);
pi_frcn_131 = in2(13,:);
pi_frcn_141 = in2(14,:);
pi_frcn_151 = in2(15,:);
pi_frcn_161 = in2(16,:);
pi_frcn_171 = in2(17,:);
pi_frcn_181 = in2(18,:);
pi_frcn_191 = in2(19,:);
pi_frcn_201 = in2(20,:);
pi_frcn_211 = in2(21,:);
pi_frcn_221 = in2(22,:);
pi_frcn_231 = in2(23,:);
pi_frcn_241 = in2(24,:);
pi_frcn_251 = in2(25,:);
pi_frcn_261 = in2(26,:);
pi_frcn_271 = in2(27,:);
pi_frcn_281 = in2(28,:);
pi_frcn_291 = in2(29,:);
pi_frcn_301 = in2(30,:);
qd1 = in1(1,:);
qd2 = in1(2,:);
qd3 = in1(3,:);
qd4 = in1(4,:);
qd5 = in1(5,:);
qd6 = in1(6,:);
qd7 = in1(7,:);
qd8 = in1(8,:);
qd9 = in1(9,:);
qd10 = in1(10,:);
tau_frcn = [pi_frcn_31+pi_frcn_11.*qd1+pi_frcn_21.*sign(qd1);pi_frcn_61+pi_frcn_41.*qd2+pi_frcn_51.*sign(qd2);pi_frcn_91+pi_frcn_71.*qd3+pi_frcn_81.*sign(qd3);pi_frcn_121+pi_frcn_101.*qd4+pi_frcn_111.*sign(qd4);pi_frcn_151+pi_frcn_131.*qd5+pi_frcn_141.*sign(qd5);pi_frcn_181+pi_frcn_161.*qd6+pi_frcn_171.*sign(qd6);pi_frcn_211+pi_frcn_191.*qd7+pi_frcn_201.*sign(qd7);pi_frcn_241+pi_frcn_221.*qd8+pi_frcn_231.*sign(qd8);pi_frcn_271+pi_frcn_251.*qd9+pi_frcn_261.*sign(qd9);pi_frcn_301+pi_frcn_281.*qd10+pi_frcn_291.*sign(qd10)];
end
