load('ptrnSrch_N7T25QR.mat');  % 載入軌跡設計結果
[q, qd, q2d] = mixed_traj(traj_par.t, c_pol, a, b, traj_par.wf, traj_par.N);

% 儲存為 .npz（Python 格式）

py.numpy.savez('trajectory_optmzn/traj_for_isaac/ptrnSrch_N7T25QR.npz', ...
    q=py.numpy.array(q'), ...
    qd=py.numpy.array(qd'), ...
    q2d=py.numpy.array(q2d'), ...
    t=py.numpy.array(traj_par.t'));
% py.numpy.savez('ur10e_traj_for_isaac.npz', q, qd, q2d, traj_par.t);
